"use client";

type Audience = { who: string; care?: string; plain: string };
type Read = { gist?: string; audiences?: Audience[]; jargon?: { term: string; plain: string }[] };

const ICON: Record<string, string> = {
  "Policymaker": "🏛️", "Investor or industry R&D": "💰", "A researcher in another field": "🔬", "The public": "🌍",
};

export default function ExplainReport({ read }: { read: Read }) {
  const r = read || {};
  return (
    <div className="space-y-5">
      {r.gist && (
        <div className="rounded-2xl border border-line bg-white p-5">
          <div className="text-xs font-semibold uppercase tracking-wide text-sage">In plain language</div>
          <p className="mt-1 text-lg font-bold leading-snug text-ink">{r.gist}</p>
        </div>
      )}

      {Array.isArray(r.audiences) && r.audiences.length > 0 && (
        <div className="grid gap-3 sm:grid-cols-2">
          {r.audiences.map((a, i) => (
            <div key={i} className="rounded-2xl border border-line bg-white p-4">
              <div className="flex items-center gap-2">
                <span className="text-xl" aria-hidden>{ICON[a.who] || "•"}</span>
                <span className="text-sm font-bold text-ink">{a.who}</span>
              </div>
              {a.care && <div className="mt-0.5 text-xs text-slate-400">{a.care}</div>}
              <p className="mt-2 text-sm leading-relaxed text-slate-700">{a.plain}</p>
            </div>
          ))}
        </div>
      )}

      {Array.isArray(r.jargon) && r.jargon.length > 0 && (
        <div className="rounded-2xl border border-line bg-white p-5">
          <div className="text-xs font-semibold uppercase tracking-wide text-slate-400">Jargon, translated</div>
          <dl className="mt-2 space-y-1.5 text-sm">
            {r.jargon.map((j, i) => (
              <div key={i} className="flex gap-2">
                <dt className="shrink-0 font-semibold text-ink">{j.term}:</dt>
                <dd className="text-slate-600">{j.plain}</dd>
              </div>
            ))}
          </dl>
        </div>
      )}

      <p className="text-xs text-slate-400">Plain-language translations of the abstract, framed for each audience. Generated by AI — check specifics against the source before quoting.</p>
    </div>
  );
}
