// GENERATED by scripts/build-exposure.mjs on 2026-08-17.
// Method: Eloundou et al. (2023) E0/E1/E2 rubric applied to public O*NET Task
// Statements (CC BY); β = (E1 + 0.5·E2)/all tasks, expressed as a percent.
// Regenerate any time; do not hand-edit.
export const EXPOSURE_DATA: Record<string, number> = {
  "11-1021": 53,
  "11-2011": 70,
  "11-2021": 73,
  "11-2022": 71,
  "11-2032": 57,
  "11-3012": 61,
  "11-3021": 53,
  "11-3031": 68,
  "11-3121": 77,
  "11-9021": 68,
  "11-9111": 67,
  "11-9199": 69,
  "13-1071": 88,
  "13-1082": 75,
  "13-1111": 73,
  "13-1151": 65,
  "13-1161": 80,
  "13-1199": 66,
  "13-2011": 71,
  "13-2051": 77,
  "15-1211": 79,
  "15-1232": 50,
  "15-1252": 55,
  "15-1255": 73,
  "15-2041": 77,
  "15-2051": 65,
  "17-2112": 73,
  "23-1011": 50,
  "23-2011": 42,
  "25-2021": 47,
  "27-1024": 71,
  "27-3031": 64,
  "27-3042": 60,
  "27-3043": 56,
  "29-1141": 61,
  "41-3091": 87,
  "41-4012": 72,
  "43-4051": 92,
  "43-6011": 55
};

export const EXPOSURE_SOURCE = "O*NET Task Statements (CC BY) × Eloundou et al. (2023) rubric, self-generated 2026-08-17";
